<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KM0QCD1" failures="1" tests="6" name="Default test" time="0.152" errors="0" timestamp="2023-12-22T19:58:23 IST">
  <testcase classname="Phase2.PracticeProject3.ElearningApp_TDD_TestNG.EcommerceTest" name="EmptyCourse" time="0.021"/>
  <testcase classname="Phase2.PracticeProject3.ElearningApp_TDD_TestNG.EcommerceTest" name="findcourse1" time="0.008"/>
  <testcase classname="Phase2.PracticeProject3.ElearningApp_TDD_TestNG.EcommerceTest" name="findcourse2" time="0.004"/>
  <testcase classname="Phase2.PracticeProject3.ElearningApp_TDD_TestNG.EcommerceTest" name="findcourse3" time="0.005"/>
  <testcase classname="Phase2.PracticeProject3.ElearningApp_TDD_TestNG.EcommerceTest" name="findcourse4" time="0.003"/>
  <testcase classname="Phase2.PracticeProject3.ElearningApp_TDD_TestNG.EcommerceTest" name="findcourse5" time="0.003">
    <failure type="java.lang.NullPointerException" message="Topic Name does not exist">
      <![CDATA[java.lang.NullPointerException: Topic Name does not exist
at Phase2.PracticeProject3.ElearningApp_TDD_TestNG.ElearningApplication.getcourse(ElearningApplication.java:32)
at Phase2.PracticeProject3.ElearningApp_TDD_TestNG.EcommerceTest.findcourse5(EcommerceTest.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- findcourse5 -->
</testsuite> <!-- Default test -->
